---
- hosts: all
  tasks:
    - name: enable banner in /etc/ssh/sshd_config
      replace:
        dest: /etc/ssh/sshd_config
        regexp: ^#Banner none
        replace: Banner /etc/ssh/sshd_banner
      become: true
    - name: copy sshd_banner to /etc/ssh/sshd_banner and set file attributes
      copy:
        src: banner.txt
        dest: /etc/ssh/sshd_banner
        owner: root
        group: root
        mode: 0400
      become: true
# requires Ansible 2.2
#    - name: restard sshd thru systemd 
#      become: true
#      systemd: 
#        name: sshd
#        state: restarted
# end

    - name: restart sshd
      become: true
      command: systemctl restart sshd.service
... 
